# Query 1
# List of procedure in progress
PREFIX eli-dl: <http://data.europa.eu/eli/eli-draft-legislation-ontology#>
PREFIX elidl: <http://data.europa.eu/eli/eli-draft-legislation-ontology#>
SELECT ?procedure ?title                 
WHERE { 
    # Look for active procedures    
    ?procedure elidl:legislative_process_status <http://data.europarl.europa.eu/authority/legislative-process-status/ACTIVE> .
    # and keep their title in English 
    ?procedure eli-dl:legislative_process_title ?title .
    FILTER langMatches(lang(?title), "en" )
}
