# Si on a une activité 'COMMITTEE_AMENDMENT' qui a un document
# et qui est liée à un dossier MAIN,
#  -> Alors relier l'amendement à l'activité du dossier MAIN

PREFIX org-ep: <http://data.europarl.europa.eu/ontology/org-ep#>
PREFIX eli-dl: <http://data.europa.eu/eli/eli-draft-legislation-ontology#>
PREFIX eli: 		<http://data.europa.eu/eli/ontology#>
PREFIX elidl-ep: 	<http://data.europarl.europa.eu/ontology/elidl-ep#>
PREFIX ep-aut:		<http://data.europarl.europa.eu/authority/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
    #4. then the document activity
    ?activity eli-dl:based_on_a_realization_of ?Document_involved .
}
WHERE {
	# 1. filter all activity Main dossier type 
    ?activity elidl-ep:activityType <http://data.europarl.europa.eu/authority/activity-type/MAIN_DOSSIER> .
    # 2. an activity created a document...
    ?activity eli-dl:consists_of ?committee_amendment .
    # 3. filter all activity COMMITTEE_AMENDMENT type
    ?committee_amendment elidl-ep:activityType <http://data.europarl.europa.eu/authority/activity-type/COMMITTEE_AMENDMENT> .
    ?committee_amendment eli-dl:involved_work ?Document_involved
}