
PREFIX ep: <http://data.europarl.europa.eu/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX eponto: <http://data.europarl.europa.eu/ontology/ep#>
PREFIX org: <http://www.w3.org/ns/org#>

SELECT 
	?Assistant
	?familyName
	?firstName
	?assistantType
	?MEP
	?MEP_familyName
    ?MEP_firstName
WHERE {
	?Assistant a ep:Assistant .	
    ?Assistant foaf:familyName ?familyName .
    ?Assistant foaf:firstName ?firstName .
    ?Assistant eponto:assistantType ?assistantType .
    ?Assistant org:hasMembership ?membership .
	?membership org:organization ?MEP	.    
    ?MEP foaf:familyName ?MEP_familyName .
    ?MEP foaf:firstName ?MEP_firstName .
}
ORDER BY ?Assistant