

SELECT 
	?Assistant
	?familyName
	?firstName
	?assistantType
	?MEP
	?MEP_familyName
    ?MEP_firstName
WHERE {
	?Assistant a ep:Assistant .	
    ?Assistant foaf:familyName ?familyName .
    ?Assistant foaf:firstName ?firstName .
    ?Assistant ep:assistantType ?assistantType .
    ?Assistant org:hasMembership ?membership .
	?membership org:organization ?MEP	.    
    ?MEP foaf:familyName ?MEP_familyName .
    ?MEP foaf:firstName ?MEP_firstName .
}
ORDER BY ?Assistant