PREFIX eponto: <http://data.europarl.europa.eu/ontology/ep#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX org: <http://www.w3.org/ns/org#>

SELECT 
	?MEP
	?firstName
	?familyName
	?persId
	?Civility
	?Gender
	?Status
	?birthCountry
	?politicalGroup

WHERE {
	?MEP a eponto:MEP .
	?MEP foaf:firstName ?firstName .
	?MEP foaf:familyName ?familyName .
	?MEP skos:notation ?persId .
	?MEP eponto:Civility/rdfs:label ?Civility .
	?MEP eponto:Gender/rdfs:label ?Gender .
	?MEP eponto:Status/rdfs:label ?Status .
	?MEP eponto:hasBirthCountry/rdfs:label ?birthCountry .
	?MEP org:hasMembership ?membership .
	?membership org:organization ?politicalGroup	.
}
ORDER BY ?MEP